export LinearGradient from './LinearGradient'
export OddGradient from './OddGradient'
export EvenGradient from './EvenGradient'
export BottomTriangleLinearGradient from './BottomTriangleLinearGradient'
export RadialGradient from './RadialGradient'
export OpacityAnimation from './OpacityAnimation'
export svgStyle from './svgStyle'
export cornerStyle from './cornerStyle'
